@baseurl=http://localhost:8080

### SignUp
POST {{baseurl}}/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "tejalsarode29@gmail.com",
    "password": "Tejal@2810",
    "name": "Tejal Sarode"
}

### login 
POST {{baseurl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

### 
POST {{baseurl}}/api/admin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MzkyOTczMjAsImV4cCI6MTczOTM4MzcyMH0.QsU5242vgV8ydP2AxQRKd32J6xTQSEhh7x16pFJMlE0

{
   "name" :"room1",
   "type": "studio",
   "price" :500
}





